# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class Annot < Formula
  desc "Human-in-the-loop annotation tool for ai workflows"
  homepage "https://github.com/denolehov/annot"
  url "https://github.com/denolehov/annot/archive/refs/tags/v0.16.0.tar.gz"
  version "0.16.0"
  sha256 "75c7ac20b354800b5518c6b7e68f3f262ded1b89bb6aabce49ec355fcedb7ba8"
  license "AGPL-3.0"

  on_macos do
    on_arm do
      url "https://github.com/denolehov/annot/releases/download/v0.16.0/annot-0.16.0-darwin-arm64.tar.gz"
      sha256 "d8e4094496eaa78c5e1c7d172697131c8ec29585bb411a3c149260b4685cd581"
    end
  end

  def install
    prefix.install "annot.app"
    bin.install_symlink prefix/"annot.app/Contents/MacOS/annot"
  end

  test do
    system bin/"annot", "--version"
  end
end
