# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class Annot < Formula
  desc "Human-in-the-loop annotation tool for ai workflows"
  homepage "https://github.com/denolehov/annot"
  url "https://github.com/denolehov/annot/releases/download/v0.7.0/annot-darwin-arm64.tar.gz"
  sha256 "311bd634ea4a00a50aabd213a5bf0461e479868ef89e634852cb3892de34ed90"
  license "AGPL-3.0"

  def install
    prefix.install "annot.app"
    bin.install_symlink prefix/"annot.app/Contents/MacOS/annot"
  end

  test do
    system bin/"annot", "--version"
  end
end
