# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class Annot < Formula
  desc "Human-in-the-loop annotation tool for ai workflows"
  homepage "https://github.com/denolehov/annot"
  url "https://github.com/denolehov/annot/archive/refs/tags/v0.17.0.tar.gz"
  version "0.17.0"
  sha256 "67b39d923ca90e0d905ee327b30f11e450f36583bf1c64319f4f24132dc11336"
  license "AGPL-3.0"

  on_macos do
    on_arm do
      url "https://github.com/denolehov/annot/releases/download/v0.17.0/annot-0.17.0-darwin-arm64.tar.gz"
      sha256 "3d8e3c9d3722d0d4c0af34e1eac39e5e3eec6837d53a69c6c83343366127b28a"
    end
  end

  def install
    prefix.install "annot.app"
    bin.install_symlink prefix/"annot.app/Contents/MacOS/annot"
  end

  test do
    system bin/"annot", "--version"
  end
end
